{% set version = environ.get('GIT_DESCRIBE_TAG', '0.1.0').strip('v') %}

package:
  name: hybridmc
  version: {{ version }}

source:
  git_url: https://github.com/Vigne-hub/hybridmc.git
  git_rev: release_hybridmc

build:
  number: 0
  script: "make release && {{ PYTHON }} setup.py install"

requirements:
  build:
    - {{ compiler('cxx') }}  # Needed for compiling C++ code
    - cmake  # For running CMake scripts
    - ninja  # Build system used by CMake for faster builds
    - python >=3.11  # Python is needed for running setup.py
    - setuptools  # setuptools is required for setup.py
    - pybind11  # Include in build as pybind11 headers are needed at compile time

  host:
    - boost  # Your project links against Boost, so it needs to be in the host to be found by CMake
    - hdf5  # Similarly, HDF5 needs to be in the host to link against it
    - python >=3.11  # Ensure Python version matches for ABI compatibility

  run:
    - python >=3.11  # Python is obviously needed at runtime
    - numpy  # Assuming your package uses NumPy at runtime
    - pandas
    - h5py
    - scipy
    - matplotlib
    - seaborn
    - nlopt
    - hybridmc_wang_landau
    - statsmodels

test:
  commands:
    - "python -c 'import wang_landau'"

about:
  home: https://github.com/Vigne-hub/hybridmc
  license: MIT
  summary: 'Hybrid Monte Carlo simulations with C++ core and Python tools wang landau process utility.'
